### ISSUE TITLE
registry not taking path

### ISSUE THREAD

**Issue by estebanefi** [bencebalogh/avro-schema-registry#13]
I am trying to use this library but my schema registry does not follow the path of `https://localhost:80/schemas/ids/{id}`, it is more like `https://localhost:80/api/v1/confluent/schemas/ids/{id}`. I would like the library to take the extra path that is provided. I noticed in fetch-schema.js that it does not append the provided path.

`
const registry = require("avro-schema-registry")(
  "http://localhost:80/api/v1/confluent/"
);
`

currently like this
```

const { protocol, host, port, auth } = registry;

   const requestOptions = {
      host,
      port,
      path: `/schemas/ids/${schemaId}`,
      auth
```

to this?
```
 const { protocol, host, port, path, auth } = registry;
 const requestOptions = {
      host,
      port,
      path: `${path}schemas/ids/${schemaId}`,
      auth

```

**Comment by bencebalogh** [comment]
It'd make sense, I'll do this soon

**Comment by estebanefi** [comment]
Thanks, it would really help.

**Comment by bencebalogh** [comment]
Out in 1.3.1
