### ISSUE TITLE
Typescript definitons don't export the function signatures

### ISSUE THREAD

**Issue by dbevan-kabam** [bencebalogh/avro-schema-registry#19]
Hey,
I've got a branch with an updated d.ts and a typescript example in the .readme. 
Here is the change
```ts
declare namespace schema {
    export type DecodeMessage = <T>(obj: Buffer, parseOptions?: any) => Promise<T>;
    export type EncodeById = (schemaId: number, msg: any, parseOptions?: any) => Promise<Buffer>;
    export type EncodeBySchema = (topic: string, schema: any, msg: any, parseOptions?: any) => Promise<Buffer>;

    export interface ISchemaRegistry {
        decode: DecodeMessage;
        decodeMessage: DecodeMessage;
        encodeById: EncodeById;
        encodeKey: EncodeBySchema;
        encodeMessage: EncodeBySchema;
    }
}

export = schema;
declare function schema(registryUrl: string) : schema.ISchemaRegistry;
```
If you can give me repository access I'll submit a PR

**Comment by katsanva** [comment]
@dbevan-kabam you don't need repository access. Just submit the PR.

**Comment by dbevan-kabam** [comment]
I get a 403 when I try to push my branch

**Comment by katsanva** [comment]
Are you sure that you have set up your credentials correctly? Also check this https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by bencebalogh** [comment]
Sorry, been away again for a bit. Thanks @katsanva for helping out!

No special permisions are needed, if after reading that link you still have issues let us know and I'll try to help.

**Comment by bencebalogh** [comment]
Out in 1.4.2
