### ISSUE TITLE
Using AUTH in url is unfriendly 

### ISSUE THREAD

**Issue by han8909227** [bencebalogh/avro-schema-registry#29]
The current method of passing in any auth would be through the registry url string, which is very unfriendly. And the method is already deprecated https://nodejs.org/api/url.html#url_urlobject_auth

We should expose an api to setup registry properly 
i.e .setRegistry(url, auth, header, etc)

**Comment by mac2000** [comment]
In my case I can not pass auth via registry url because of special symbols

**Comment by bencebalogh** [comment]
Not strictly against it, in which cases do you want to pass additional headers to the schema registry?

Can you please both check the PR and comment if it fixes the issues?

@mac2000 Can you please give me an example which doesn't work to check if it is still an issue with the new version?

**Comment by mac2000** [comment]
Looking at your code it should not be a problem

In my case imagine that you have `@` symbol in password, which makes impossible to curl `https://username:password@example.com`

**Comment by bencebalogh** [comment]
Fixed in `2.0.0`
