### ISSUE TITLE
Feature request: decodeKey and encodeKey

### ISSUE THREAD

**Issue by mangvlad** [bencebalogh/avro-schema-registry#3]
Any way to add the same functionality to use for keys?

Thanks!

**Comment by bencebalogh** [comment]
It's something that should be done, I'll add a 2nd parameter with default to value to determine if it's a key or value to encode/decode, that way it's not a breaking change to previous versions.

**Comment by mangvlad** [comment]
Thank you!

**Comment by bencebalogh** [comment]
Published in 1.1.0
