### ISSUE TITLE
Problem in encoding message using encodeMessage method for new topic with no schema

### ISSUE THREAD

**Issue by NishantNaithani** [bencebalogh/avro-schema-registry#43]
Hello,
When I am trying to encode a message using the _encodeMessage_ method for any new topic for which we do not have any schema in our Schema Registry, the _pushSchema_ method is throwing a 500 Error.

`Error: Schema registry error: 500 - Internal Server Error`

And when I tried with updating some code in http-calls.js file, it worked for me. The changes made were:

` const body = {`
    `schema: JSON.stringify(requestedSchema)`
  `};`

`req.write(JSON.stringify(body));`

**Comment by bencebalogh** [comment]
Thanks for spotting this, fixed in `2.1.1`
