### ISSUE TITLE
Option for passing additional headers

### ISSUE THREAD

**Issue by ashetga** [bencebalogh/avro-schema-registry#44]
Hello,

Is there any option for passing additional headers. I access a third-party schema registry through a gateway and gateway expects me to send below header:

'Content-Type': 'application/vnd.schemaregistry.v1+json'

The gateway currently rejects all requests without this header.
Is there any option for achieving this?

Thanks,
Akshay

**Comment by bencebalogh** [comment]
This header used to be in the call, got removed by accident during a refactor. I've added it back in 2.1.1, if you still have a need after this to pass optional headers please reopen the issue.
