### ISSUE TITLE
Missing content-type header in getSchemaById call

### ISSUE THREAD

**Issue by ashetga** [bencebalogh/avro-schema-registry#45]
Hello,

This is related to the below-mentioned issue which I had raised previously.

https://github.com/bencebalogh/avro-schema-registry/issues/44

I see that you have added the header to pushSchema call. 
Is it possible to add it to getSchemaById and getLatestVersionForSubject calls in the same class as well?
I'm using the decode function which internally calls getSchemaById call to retrieve the schema.

Thanks,
Akshay

**Comment by bencebalogh** [comment]
Published this in 2.1.2

Let me know if there's anything else
