### ISSUE TITLE
It parses schema every time when decoding

### ISSUE THREAD

**Issue by v3i1r4in** [bencebalogh/avro-schema-registry#47]
Any reason we are caching string schema instead of parsed schema? It introduces a huge latency when decoding.

**Comment by bencebalogh** [comment]
Where the schema is stored it's always called as ```registry.cache.setById(id, Promise.resolve(parsedSchema))``` where `parsedSchema` is `avsc.parse(schema, parseOptions)`. Where do you see the lib storing the schema as a string?

**Comment by v3i1r4in** [comment]
This line https://github.com/bencebalogh/avro-schema-registry/blob/master/registry.js#L107. It’s called after you get the schema from cache.

**Comment by bencebalogh** [comment]
Fixed in v2.1.4
