### ISSUE TITLE
Fallback schema registry URLs

### ISSUE THREAD

**Issue by jpzk** [bencebalogh/avro-schema-registry#7]
In a fault-tolerant cluster environment one has multiple schema registries for fail-over. This might not be hard to implement but it will be crucial for enterprise use of the library. Kudos, library is working fine so far!

**Comment by bencebalogh** [comment]
Sorry for forgetting about this.

Do you have some ideas how the fallback should behave? Would it be a list of URLs and if it fails it just cycles to the next one and tries that? After one failure should it always stick to the first found successful fallback one and should it try after, if that starts failing, the previously failed ones?

**Comment by bencebalogh** [comment]
Closing until more people are asking for it and we come up with a solution to implement
